# Generated by Django 2.2.3 on 2020-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=255)),
                ('adminpass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=3)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('joiningdate', models.DateField()),
                ('endingdate', models.DateField()),
            ],
        ),
    ]
