# Generated by Django 2.2.3 on 2020-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymattendeceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
