# Generated by Django 2.2.3 on 2020-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymattendeceapp', '0002_auto_20200310_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='endingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='joiningdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
