# Generated by Django 2.2.3 on 2020-03-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymattendeceapp', '0006_auto_20200314_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='endingdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='joiningdate',
            field=models.DateTimeField(),
        ),
    ]
