# Generated by Django 2.2.3 on 2020-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymattendeceapp', '0007_auto_20200314_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='endingdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='joiningdate',
            field=models.DateField(),
        ),
    ]
